USE startersql;
-- SELECT * FROM users;
-- SELECT * FROM users WHERE gender="Female";
--  SELECT * FROM users WHERE gender="Male";
-- SELECT * FROM users WHERE gender!="Female";
-- SELECT * FROM users WHERE gender="Male";
-- SELECT * FROM users WHERE date_of_birth<'1995-09-09';
-- SELECT * FROM users WHERE id>10;
-- SELECT * FROM users WHERE date_of_birth BETWEEN'1995-09-09' AND '1999-09-09';
-- SELECT * FROM users WHERE gender IN('male', 'Female');
-- SELECT * FROM users WHERE gender='Female' AND salary>'70000';
-- SELECT * FROM users WHERE gender='Male' AND salary<'70000';
-- SELECT * FROM users WHERE gender='Male' OR salary>'65000';
-- SELECT * FROM users WHERE gender='Male' OR salary>'65000' ORDER BY date_of_birth ASC;
-- SELECT * FROM users WHERE gender='Male' OR salary>'65000' ORDER BY date_of_birth DESC;
-- SELECT * FROM users WHERE gender='Male' OR salary>'65000' ORDER BY date_of_birth ASC LIMIT 5;
-- SELECT * FROM users WHERE gender='Male' OR salary>'65000' LIMIT 6;
-- SELECT * FROM users WHERE salary > 60000 ORDER BY created_at DESC;
-- SELECT * FROM users ORDER BY salary DESC; 
SELECT * FROM users WHERE salary BETWEEN 50000 AND 70000;
