USE startersql;
SELECT * FROM users;
-- SELECT COUNT(*) FROM users;
-- SELECT COUNT(*) FROM users WHERE gender = 'female';
-- SELECT COUNT(*) FROM users WHERE gender = 'Male';
-- SELECT MIN(salary) AS min_salary, MAX(salary) AS max_salary FROM users;
-- SELECT SUM(salary) AS total_sal FROM users;
-- SELECT AVG(Salary) AS avg_sal FROM users;
-- SELECT gender, AVG(Salary) AS avg_sal FROM users GROUP BY gender;
-- SELECT id, gender, AVG(Salary) AS avg_sal FROM users GROUP BY id;
-- SELECT gender, SUM(Salary) AS avg_sal FROM users GROUP BY gender;
-- SELECT id, gender, name, LENGTH(name) AS name_len FROM users;
-- SELECT id, gender, name, LOWER(name)  AS lower, LENGTH(name) AS name_len FROM users;
-- SELECT id, gender, name, UPPER(name)  AS upper, LENGTH(name) AS name_len FROM users;
-- SELECT id, gender, UPPER(name)  AS upper, CONCAT(LOWER(name), '1234') AS username, LENGTH(name) AS name_len FROM users;
-- SELECT id, gender, UPPER(name)  AS upper, CONCAT(LOWER(name), '1234') AS username,NOW() as time, LENGTH(name) AS name_len FROM users;
-- SELECT id, gender, UPPER(name)  AS upper, CONCAT(LOWER(name), '1234') AS username,YEAR(date_of_birth) as year, LENGTH(name) AS name_len FROM users;
-- SELECT id, gender, UPPER(name)  AS upper, CONCAT(LOWER(name), '1234') AS username,DAY(date_of_birth) as day,YEAR(date_of_birth) as year, LENGTH(name) AS name_len FROM users;
-- SELECT id, gender, UPPER(name)  AS upper, CONCAT(LOWER(name), '1234') AS username,DAYNAME(date_of_birth) as day,MONTHNAME(date_of_birth) AS month, YEAR(date_of_birth) as year, LENGTH(name) AS name_len FROM users;
SELECT name, DATEDIFF(CURDATE(), date_of_birth) AS days FROM users;